INSERT INTO [DEX-HC].dbo.Value (Id,Name,[Data],Unit_Value,SKU,Id_Field,Id_Parent) VALUES 
(73,'Lineal','{"index":0,"title":"Lineal","imgUrl":"assets/images/kitchen-precotizer/lineal/base_lineal.jpg","selected":false, "unitPrice": 0}',0,NULL,1,NULL)
,(74,'En L','{"index":1,"title":"En L","imgUrl":"assets/images/kitchen-precotizer/en_l/base_L.jpg","selected":false, "unitPrice": 0}',0,NULL,1,NULL)
,(75,'En U','{"index":2,"title":"En U","imgUrl":"assets/images/kitchen-precotizer/en_u/base_U.jpg","selected":false, "unitPrice": 0}',0,NULL,1,NULL)
,(76,'Lineal con isla','{"index":3,"title":"Lineal con isla","imgUrl":"assets/images/kitchen-precotizer/lineal_con_isla/base_lineal_isla.jpg","selected":false, "unitPrice": 0}',0,NULL,1,NULL)
,(77,'Amaderados','{"index":0,"title":"Amaderados","imgUrl":"assets/images/kitchen-precotizer/melamina.png","selected":false, "unitPrice": 1300000,"features":"Amaderados"}',0,NULL,4,NULL)
,(78,'Alto brillo','{"index":1,"title":"Alto brillo","imgUrl":"assets/images/kitchen-precotizer/highgloss.png","selected":false, "unitPrice": 1600000,"features":"Alto brillo"}',0,NULL,4,NULL)
,(79,'Granito','{"index":0,"title":"Granito","imgUrl":"assets/images/kitchen-precotizer/granito.jpg","selected":false, "unitPrice": 390000,"features":"Piedra natural en Granito. Estos, son productos de la naturaleza y por lo tanto, están sujetos a variaciones cromáticas."}',0,NULL,5,NULL)
,(80,'Quartzone','{"index":1,"title":"Quartzone","imgUrl":"assets/images/kitchen-precotizer/quartzone.jpg","selected":false, "unitPrice": 690000,"features":"Los Quarztone son productos artificiales y por lo tanto, pueden presentar ligeras variaciones cromáticas."}',0,NULL,5,NULL)
,(81,'Doble','{"index":0,"title":"Doble","imgUrl":"assets/images/kitchen-precotizer/doble.jpg","selected":false, "unitPrice": 220000}',0,NULL,6,NULL)
,(82,'Sencillo','{"index":1,"title":"Sencillo","imgUrl":"assets/images/kitchen-precotizer/sencillo.jpg","selected":false, "unitPrice": 110000}',0,NULL,6,NULL)
;
INSERT INTO [DEX-HC].dbo.Value (Id,Name,[Data],Unit_Value,SKU,Id_Field,Id_Parent) VALUES 
(83,'Escurreplatos','{"index":0,"title":"Escurreplatos","imgUrl":"assets/images/kitchen-precotizer/escurreplatos.jpg","selected":false, "unitPrice": 66000}',0,NULL,7,NULL)
,(84,'Basurero','{"index":1,"title":"Basurero","imgUrl":"assets/images/kitchen-precotizer/basurero.png","selected":false, "unitPrice": 86000}',0,NULL,7,NULL)
,(85,'Canasta multiusos','{"index":2,"title":"Canasta multiusos","imgUrl":"assets/images/kitchen-precotizer/canasta_multiusos.jpg","selected":false, "unitPrice": 120000}',0,NULL,7,NULL)
,(86,'Canasta para utensilios','{"index":3,"title":"Canasta para utensilios","imgUrl":"assets/images/kitchen-precotizer/canasta_para_utensilios.jpg","selected":false, "unitPrice": 136000}',0,NULL,7,NULL)
,(87,'Todo el hogar','{"index":0,"title":"Todo el hogar","imgUrl":"assets/images/floors-walls/todo-el-hogar.png","selected":false, "unitPrice": 0}',0,NULL,8,NULL)
,(88,'Cocina','{"index":1,"title":"Cocina","imgUrl":"assets/images/floors-walls/cocina.png","selected":false, "unitPrice": 0}',0,NULL,8,NULL)
,(89,'Sala comedor','{"index":2,"title":"Sala comedor","imgUrl":"assets/images/floors-walls/sala-comedor.png","selected":false, "unitPrice": 0}',0,NULL,8,NULL)
,(90,'Baño','{"index":3,"title":"Baño","imgUrl":"assets/images/floors-walls/bano.png","selected":false, "unitPrice": 0}',0,NULL,8,NULL)
,(91,'Habitación','{"index":4,"title":"Habitación","imgUrl":"assets/images/floors-walls/habitacion.png","selected":false, "unitPrice": 0}',0,NULL,8,NULL)
,(92,'Garaje','{"index":5,"title":"Garaje","imgUrl":"assets/images/floors-walls/autos.png","selected":false, "unitPrice": 0}',0,NULL,8,NULL)
;
INSERT INTO [DEX-HC].dbo.Value (Id,Name,[Data],Unit_Value,SKU,Id_Field,Id_Parent) VALUES 
(93,'Espacio abierto','{"index":6,"title":"Espacio abierto","imgUrl":"assets/images/floors-walls/espacio-abierto.png","selected":false, "unitPrice": 0}',0,NULL,8,NULL)
,(94,'Piso','{"index":0,"title":"Piso","imgUrl":"assets/images/floors-walls/piso.png","selected":false, "unitPrice": 1300000,"features":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed laoreet eget lectus non sollicitudin."}',0,NULL,11,NULL)
,(95,'Pared','{"index":1,"title":"Pared","imgUrl":"assets/images/floors-walls/pared.png","selected":false, "unitPrice": 1600000,"features":"Lorem ipsum dolor sit amet, consectetur adipiscing elit."}',0,NULL,11,NULL)
,(96,'Cerámica','{"index":0,"title":"Cerámica","imgUrl":"assets/images/floors-walls/ceramica.png","selected":false, "unitPrice": 132000,"features":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed laoreet eget lectus non sollicitudin."}',0,NULL,12,NULL)
,(97,'Porcelanato','{"index":1,"title":"Porcelanato","imgUrl":"assets/images/floors-walls/porcelanato.png","selected":false, "unitPrice": 390000,"features":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed laoreet eget lectus non sollicitudin."}',0,NULL,12,NULL)
,(98,'Granito','{"index":0,"title":"Granito","imgUrl":"assets/images/inns/granito.png","selected":false, "unitPrice": 390000,"features":"Piedra natural en Granito. Estos, son productos de la naturaleza y por lo tanto, están sujetos a variaciones cromáticas."}',0,NULL,14,NULL)
,(99,'Quartzone','{"index":1,"title":"Quartzone","imgUrl":"assets/images/inns/quartzone.png","selected":false, "unitPrice": 690000,"features":"Los Quarztone son productos artificiales y por lo tanto, pueden presentar ligeras variaciones cromáticas."}',0,NULL,14,NULL)
,(100,'Negro San gabriel','{"index":0,"title":"Negro San Gabriel","imgUrl":"assets/images/inns/san_gabriel.png","selected":false, "unitPrice": 0}',0,NULL,15,98)
,(101,'Gris clásico','{"index":0,"title":"Gris clásico","imgUrl":"assets/images/inns/gris_clasico.png","selected":false, "unitPrice": 0}',0,NULL,15,99)
,(102,'Salmón Brown','{"index":1,"title":"Salmón Brown","imgUrl":"assets/images/inns/salmon_brown.png","selected":false, "unitPrice": 0}',0,NULL,15,98)
;
INSERT INTO [DEX-HC].dbo.Value (Id,Name,[Data],Unit_Value,SKU,Id_Field,Id_Parent) VALUES 
(103,'Blanco Polar','{"index":1,"title":"Blanco Polar","imgUrl":"assets/images/inns/blanco_polar.png","selected":false, "unitPrice": 0}',0,NULL,15,99)
,(104,'Todo el hogar','{"index":0,"title":"Todo el hogar","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0}',0,NULL,16,NULL)
,(105,'Cocina','{"index":1,"title":"Cocina","imgUrl":"assets/images/diva/cocina.png","selected":false, "unitPrice": 0}',0,NULL,16,NULL)
,(106,'Sala comedor','{"index":2,"title":"Sala comedor","imgUrl":"assets/images/diva/sala_comedor.png","selected":false, "unitPrice": 0}',0,NULL,16,NULL)
,(107,'Baño','{"index":3,"title":"Baño","imgUrl":"assets/images/diva/baño.png","selected":false, "unitPrice": 0}',0,NULL,16,NULL)
,(108,'Habitación','{"index":4,"title":"Habitación","imgUrl":"assets/images/diva/habitacion.png","selected":false, "unitPrice": 0}',0,NULL,16,NULL)
,(109,'Estudio','{"index":5,"title":"Estudio","imgUrl":"assets/images/diva/estudio.png","selected":false, "unitPrice": 0}',0,NULL,16,NULL)
,(110,'Enrollable blackout','{"index":0,"title":"Enrollable blackout","imgUrl":"assets/images/diva/diseño/cortina_enrollable_blackout.png","selected":false, "unitPrice": 0}',0,NULL,17,NULL)
,(111,'Enrollable solar screen','{"index":1,"title":"Enrollable solar screen","imgUrl":"assets/images/diva/diseño/cortina_enrollable_solar_screen.png","selected":false, "unitPrice": 0}',0,NULL,17,NULL)
,(112,'Enrollable traslucida','{"index":2,"title":"Enrollable traslucida","imgUrl":"assets/images/diva/diseño/cortina_enrollable_traslucida.png","selected":false, "unitPrice": 0}',0,NULL,17,NULL)
;
INSERT INTO [DEX-HC].dbo.Value (Id,Name,[Data],Unit_Value,SKU,Id_Field,Id_Parent) VALUES 
(113,'Cortina panel japonés','{"index":3,"title":"Cortina panel japonés","imgUrl":"assets/images/diva/diseño/cortina_panel_japones.png","selected":false, "unitPrice": 0}',0,NULL,17,NULL)
,(114,'Enrollable roler duo','{"index":4,"title":"Enrollable roler duo","imgUrl":"assets/images/diva/diseño/cortina_enrollable_roler_duo.png","selected":false, "unitPrice": 0}',0,NULL,17,NULL)
,(115,'Persiana horizontal de madera 50 mm','{"index":5,"title":"Persiana horizontal de madera 50 mm","imgUrl":"assets/images/diva/diseño/persiana_horizontal_de_madera_50_mm.png","selected":false, "unitPrice": 0}',0,NULL,17,NULL)
,(116,'Absolut Blackout','{"index":0,"title":"Absolut Blackout","imgUrl":"assets/images/diva/coleccion/blackout_absolut.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): 100% Oscuridad, Fácil Limpieza, Acabado Fibra de Vidrio", "privacy": 20}',0,NULL,18,110)
,(117,'Absolut Terra','{"index":1,"title":"Terra Blackout","imgUrl":"assets/images/diva/coleccion/blackout_terra.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): 100% Oscuridad, Acabado tipo tela poliester", "privacy": 20}',0,NULL,18,110)
,(118,'Solar screen 10%','{"index":0,"title":"Solar Screen Apertura 10%","imgUrl":"assets/images/diva/coleccion/solar_screen_10.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Tela con cubrimiento de PVC, 90% protección UV, Perfecta Iluminación de espacios y confort visual, fácil limpieza, antihongos.", "privacy": 20}',0,NULL,18,111)
,(119,'Solar screen 5%','{"index":1,"title":"Solar Screen Apertura 5%","imgUrl":"assets/images/diva/coleccion/solar_screen_5.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Tela con cubrimiento de PVC, 95% protección UV, Perfecta Iluminación de espacios y confort visual, fácil limpieza.", "privacy": 20}',0,NULL,18,111)
,(120,'Solar screen 3%','{"index":2,"title":"Solar Screen Apertura 3%","imgUrl":"assets/images/diva/coleccion/solar_screen_3.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Tela con cubrimiento de PVC, 90% protección UV, Perfecta Iluminación de espacios, fácil limpieza.", "privacy": 20}',0,NULL,18,111)
,(121,'Solar Screen Natura','{"index":3,"title":"Solar Screen Natura","imgUrl":"assets/images/diva/coleccion/solar_screen_natura.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Tela decorativa con cubrimiento de PVC, protección UV, Perfecta Iluminación de espacios, fácil limpieza, retardante al fuego.", "privacy": 20}',0,NULL,18,111)
,(122,'Solar screen damasco','{"index":4,"title":"Solar Screen Decorativa Damasco","imgUrl":"assets/images/diva/coleccion/solar_screen_damasco.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Tela decorativa, 88% protección UV, Perfecta Iluminación de espacios y confort visual, fácil limpieza, antihongos.", "privacy": 20}',0,NULL,18,111)
;
INSERT INTO [DEX-HC].dbo.Value (Id,Name,[Data],Unit_Value,SKU,Id_Field,Id_Parent) VALUES 
(123,'Traslúcida Decorativa Cross Texture','{"index":0,"title":"Traslúcida Decorativa Cross Texture","imgUrl":"assets/images/diva/coleccion/traslucida_decorativa_cross_texture.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Tela decorativa 100% poliester, con nivel de privacidad alto, perfecta iluminación de espacios, acabado texturizado.", "privacy": 20}',0,NULL,18,112)
,(124,'Traslúcida Decorativa Biaggio','{"index":1,"title":"Traslúcida Decorativa Biaggio","imgUrl":"assets/images/diva/coleccion/traslucida_decorativa_biaggio.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Tela decorativa 100% poliester, con nivel de privacidad bajo, perfecta iluminación de espacios, alta visibilidad, rayas verticales.", "privacy": 20}',0,NULL,18,112)
,(125,'Traslúcida Decorativa Riviera','{"index":2,"title":"Traslúcida Decorativa Riviera","imgUrl":"assets/images/diva/coleccion/traslucida_decorativa_riviera.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Tela decorativa 100% poliester, con nivel de privacidad alto, perfecta iluminación de espacios, rayas verticales.", "privacy": 20}',0,NULL,18,112)
,(126,'Panel Solar screen apertura 5%','{"index":0,"title":"Panel Solar screen apertura 5%","imgUrl":"assets/images/diva/coleccion/panel_solar_screen_5.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Tela con cubrimiento de PVC, 95% protección UV, Perfecta Iluminación de espacios y confort visual, fácil limpieza.", "privacy": 20}',0,NULL,18,113)
,(127,'Panel Solar screen apertura 10%','{"index":1,"title":"Panel Solar screen apertura 10%","imgUrl":"assets/images/diva/coleccion/panel_solar_screen_10.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Tela con cubrimiento de PVC, 90% protección UV, Perfecta Iluminación de espacios y confort visual, fácil limpieza, antihongos.", "privacy": 20}',0,NULL,18,113)
,(128,'Panel traslúcido blaggio','{"index":2,"title":"Panel traslúcido blaggio","imgUrl":"assets/images/diva/coleccion/panel_traslucido_biaggio.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Tela decorativa 100% poliester, con nivel de privacidad bajo, perfecta iluminación de espacios, alta visibilidad, rayas verticales.", "privacy": 20}',0,NULL,18,113)
,(129,'Sheer Elegance Classic','{"index":0,"title":"Sheer Elegance Classic","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Cortina con franjas de traslape, tela poliester, malla decorativa. Paso de luz y alto grado de privacidad", "privacy": 20}',0,NULL,18,114)
,(130,'Sheer Elegance Solar Screen Prado','{"index":1,"title":"Sheer Elegance Solar Screen Prado","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Cortina con franjas de traslape, Tela con cubrimiento de PVC, protección UV, Perfecta Iluminación de espacios, Confort Visual, Fácil Limpieza", "privacy": 20}',0,NULL,18,114)
,(131,'Sheer Elegance Linen','{"index":2,"title":"Sheer Elegance Linen","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Cortina con franjas de traslape, tela poliester, malla decorativa. Paso de luz y alto grado de privacidad", "privacy": 20}',0,NULL,18,114)
,(132,'Sheer Elegance Flamenco','{"index":3,"title":"Sheer Elegance Flamenco","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Cortina con franjas de traslape, tela poliester, velo decorativo. Paso de luz y alto grado de privacidad", "privacy": 20}',0,NULL,18,114)
;
INSERT INTO [DEX-HC].dbo.Value (Id,Name,[Data],Unit_Value,SKU,Id_Field,Id_Parent) VALUES 
(133,'Sheer Elegance Murano','{"index":4,"title":"Sheer Elegance Murano","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Cortina con franjas de traslape, tela poliester, velo decorativo. Paso de luz y alto grado de privacidad", "privacy": 20}',0,NULL,18,114)
,(134,'Sheer Elegance Blackout Misty','{"index":5,"title":"Sheer Elegance Blackout Misty","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Cortina con franjas de traslape, tela poliester, velo decorativo. Nivel de provacidad y oscuridad alto. Ideal para habitaciones", "privacy": 20}',0,NULL,18,114)
,(135,'Sheer Elegance Dark XL','{"index":6,"title":"Sheer Elegance Dark XL","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Cortina con franjas de traslape, tela poliester, velo decorativo. Paso de luz bajo y alto grado de privacidad", "privacy": 20}',0,NULL,18,114)
,(136,'Sheer Elegance Creppe','{"index":7,"title":"Sheer Elegance Creppe","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Cortina con franjas de traslape, tela poliester, velo decorativo. Paso de luz y alto grado de privacidad", "privacy": 20}',0,NULL,18,114)
,(137,'Sheer Elegance Style','{"index":8,"title":"Sheer Elegance Style","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Cortina con franjas de traslape, tela poliester, velo decorativo. Paso de luz y alto grado de privacidad", "privacy": 20}',0,NULL,18,114)
,(138,'Sheer Elegance Trendy','{"index":9,"title":"Sheer Elegance Trendy","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Cortina con franjas de traslape, tela poliester, velo decorativo. Paso de luz y alto grado de privacidad", "privacy": 20}',0,NULL,18,114)
,(139,'Sheer Elegance Oasis','{"index":10,"title":"Sheer Elegance Oasis","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Cortina con franjas de traslape, tela poliester, velo decorativo. Paso de luz y alto grado de privacidad", "privacy": 20}',0,NULL,18,114)
,(140,'Persiana Madera Alaska','{"index":0,"title":"Persiana Madera Alaska","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0,"features":"Colección (Tipo de tela): Madera 100% Natural de alta durabilidad. Aporta elegancia y calidez para estilos tradicionales.", "privacy": 20}',0,NULL,18,115)
,(141,'Persiana Madera Avellana','{"index":1,"title":"Persiana Madera Avellana","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Madera 100% Natural de alta durabilidad. Aporta elegancia y calidez para estilos tradicionales.", "privacy": 20}',0,NULL,18,115)
,(142,'Persiana Madera Marmol','{"index":2,"title":"Persiana Madera Marmol","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Madera 100% Natural de alta durabilidad. Aporta elegancia y calidez para estilos tradicionales.", "privacy": 20}',0,NULL,18,115)
;
INSERT INTO [DEX-HC].dbo.Value (Id,Name,[Data],Unit_Value,SKU,Id_Field,Id_Parent) VALUES 
(143,'Persiana Madera Nuez','{"index":3,"title":"Persiana Madera Nuez","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Madera 100% Natural de alta durabilidad. Aporta elegancia y calidez para estilos tradicionales.", "privacy": 20}',0,NULL,18,115)
,(144,'Persiana Madera Roble','{"index":4,"title":"Persiana Madera Roble","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Madera 100% Natural de alta durabilidad. Aporta elegancia y calidez para estilos tradicionales.", "privacy": 20}',0,NULL,18,115)
,(145,'Beige','{"index":1,"title":"Beige","imgUrl":"assets/images/diva/diseño/blackout/beige.png","selected":false, "unitPrice": 0}',0,NULL,19,116)
,(146,'Gris','{"index":2,"title":"Gris","imgUrl":"assets/images/diva/diseño/blackout/gris.png","selected":false, "unitPrice": 0}',0,NULL,19,116)
,(147,'Todo el hogar','{"index":0, "title":"Todo el hogar", "imgUrl": "assets/images/ilumination/todo_el_hogar.png", "selected":false, "unitPrice": 0}',0,NULL,22,NULL)
,(148,'Cocina','{"index":1, "title":"Cocina", "imgUrl": "assets/images/ilumination/cocina.png", "selected":false, "unitPrice": 0}',0,NULL,22,NULL)
,(149,'Sala comedor','{"index":2, "title":"Sala comedor", "imgUrl": "assets/images/ilumination/sala_comedor.png", "selected":false, "unitPrice": 0}',0,NULL,22,NULL)
,(150,'1 Agua','{"index":0, "title":"1 Agua", "imgUrl": "assets/images/roof-tiles/un_agua.png", "selected":false, "unitPrice": 0}',0,NULL,25,NULL)
,(151,'2 Aguas','{"index":1, "title":"2 Aguas", "imgUrl": "assets/images/roof-tiles/dos_agua.png", "selected":false, "unitPrice": 0}',0,NULL,25,NULL)
,(152,'3 Aguas','{"index":2, "title":"3 Aguas", "imgUrl": "assets/images/roof-tiles/tres_aguas.png", "selected":false, "unitPrice": 0}',0,NULL,25,NULL)
;
INSERT INTO [DEX-HC].dbo.Value (Id,Name,[Data],Unit_Value,SKU,Id_Field,Id_Parent) VALUES 
(153,'4 Aguas','{"index":3, "title":"4 Aguas", "imgUrl": "assets/images/roof-tiles/cuatro_aguas.png", "selected":false, "unitPrice": 0}',0,NULL,25,NULL)
,(154,'UPVC','{"index":0, "title":"UPVC", "imgUrl": "assets/images/roof-tiles/upvc.png", "selected":false, "unitPrice": 0}',0,NULL,26,NULL)
,(155,'Plastica','{"index":1, "title":"Plastica", "imgUrl": "assets/images/roof-tiles/plastica.png", "selected":false, "unitPrice": 0}',0,NULL,26,NULL)
,(156,'Fibrocemento','{"index":2, "title":"Fibrocemento", "imgUrl": "assets/images/roof-tiles/fibrocemento.png", "selected":false, "unitPrice": 0}',0,NULL,26,NULL)
,(157,'Policarbonato','{"index":3, "title":"Policarbonato", "imgUrl": "assets/images/roof-tiles/policarbonato.png", "selected":false, "unitPrice": 0}',0,NULL,26,NULL)
,(158,'Barro','{"index":4, "title":"Barro", "imgUrl": "assets/images/roof-tiles/barro.png", "selected":false, "unitPrice": 0}',0,NULL,26,NULL)
,(159,'Metalicas','{"index":5, "title":"Metalicas", "imgUrl": "assets/images/roof-tiles/metalicas.png", "selected":false, "unitPrice": 0}',0,NULL,26,NULL)
,(160,'Rojo','{"index":0, "title":"Rojo", "imgUrl": "assets/images/roof-tiles/rojo.png", "selected":false, "unitPrice": 0}',0,NULL,30,165)
,(161,'Azul','{"index":1, "title":"Azul", "imgUrl": "assets/images/roof-tiles/azul.png", "selected":false, "unitPrice": 0}',0,NULL,30,165)
,(162,'Verde','{"index":2, "title":"Verde", "imgUrl": "assets/images/roof-tiles/verde.png", "selected":false, "unitPrice": 0}',0,NULL,30,165)
;
INSERT INTO [DEX-HC].dbo.Value (Id,Name,[Data],Unit_Value,SKU,Id_Field,Id_Parent) VALUES 
(163,'Blanco','{"index":3, "title":"Blanco", "imgUrl": "assets/images/roof-tiles/blanco.png", "selected":false, "unitPrice": 0}',0,NULL,30,165)
,(164,'upvc-2mm','{"index":0, "title":"2mm"}',0,NULL,27,154)
,(165,'upvc-2.5mm','{"index":1, "title":"2,5mm"}',0,NULL,27,154)
,(166,'plastica-2.2mm','{"index":0, "title":"2,2mm"}',0,NULL,27,155)
,(167,'plastica-2.6mm','{"index":1, "title":"2,2mm"}',0,NULL,27,155)
,(168,'light-yellow','{"index":0, "title":"Luz amarilla", "descripcion":"Ambiente acogedor", "recomendation":"Ideal para:" "imageOn":"assets/images/ilumination/yellow_on.png", "imageOff":"assets/images/ilumination/yellow_off.png"}',0,NULL,23,NULL)
,(169,'light-day','{"index":1, "title":"Luz día", "descripcion":"Efecto natural", "recomendation":"Ideal para:", "imageOn":"assets/images/ilumination/daylight_on.png", "imageOff":"assets/images/ilumination/daylight_off.png"}',0,NULL,23,NULL)
,(170,'light-white','{"index":2, "title":"Luz blanca", "descripcion":"Facilita la atención", "recomendation":"Ideal para:", "imageOn":"assets/images/ilumination/white_on.png", "imageOff":"assets/images/ilumination/white_off.png"}',0,NULL,23,NULL)
,(171,'led','{"index":0, "title":"Luz LED", "description":"Te brinda una iluminación perfecta ahorrando hasta un", "image":"assets/images/ilumination/led.png"}',0,NULL,24,NULL)
,(173,'Panel  traslúcido graphics','{"index":3,"title":"Panel  traslúcido graphics","imgUrl":"assets/images/diva/coleccion/panel_traslucido_graphics.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Tela Traslucida con diseño, 100% poliester. Permite paso de Luz con grado de privacidad medio.", "privacy": 20}',0,NULL,18,113)
;
INSERT INTO [DEX-HC].dbo.Value (Id,Name,[Data],Unit_Value,SKU,Id_Field,Id_Parent) VALUES 
(174,'Rayas verticales riviera','{"index":4,"title":"Rayas verticales riviera","imgUrl":"assets/images/diva/hogar.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Tela Semitraslucida con rayas vericales, Permite paso de Luz con grado medio de privacidad.", "privacy": 20}',0,NULL,18,113)
,(175,'Traslúcido cross texture','{"index":5,"title":"Traslúcido cross texture","imgUrl":"assets/images/diva/coleccion/traslucido_cross_texture.png","selected":false, "unitPrice": 0, "features":"Colección (Tipo de tela): Tela Traslucida Texturizada, Permite paso de Luz con alto grado de privacidad.", "privacy": 20}',0,NULL,18,113)
,(176,'Blanco','{"index":0,"title":"Blanco","imgUrl":"assets/images/diva/diseño/blackout/blanco.png","selected":false, "unitPrice": 0}',0,'',19,116)
;